curl -o assets/images/canva.svg https://cdn.worldvectorlogo.com/logos/canva-1.svg
curl -o assets/images/figma.svg https://cdn.worldvectorlogo.com/logos/figma-1.svg
curl -o assets/images/vscode.svg https://cdn.worldvectorlogo.com/logos/visual-studio-code-1.svg
curl -o assets/images/github.svg https://cdn.worldvectorlogo.com/logos/github-icon-1.svg
curl -o assets/images/mysqlworkbench.svg https://cdn.worldvectorlogo.com/logos/mysql-workbench.svg
curl -o assets/images/firebase.svg https://cdn.worldvectorlogo.com/logos/firebase-1.svg
curl -o assets/images/postman.svg https://cdn.worldvectorlogo.com/logos/postman.svg
curl -o assets/images/html.svg https://cdn.worldvectorlogo.com/logos/html-1.svg
curl -o assets/images/css.svg https://cdn.worldvectorlogo.com/logos/css-3.svg
curl -o assets/images/tailwind.svg https://cdn.worldvectorlogo.com/logos/tailwind-css-1.svg
curl -o assets/images/react.svg https://cdn.worldvectorlogo.com/logos/react-1.svg
curl -o assets/images/mysql.svg https://cdn.worldvectorlogo.com/logos/mysql-1.svg
curl -o assets/images/javascript.svg https://cdn.worldvectorlogo.com/logos/javascript-1.svg
curl -o assets/images/php.svg https://cdn.worldvectorlogo.com/logos/php-1.svg
curl -o assets/images/java.svg https://cdn.worldvectorlogo.com/logos/java-1.svg
curl -o assets/images/c.svg https://cdn.worldvectorlogo.com/logos/c-1.svg
curl -o assets/images/cpp.svg https://cdn.worldvectorlogo.com/logos/c.svg
